name: Release

on:
  push:
    tags: [v*]
    branches: [main]
  pull_request:

permissions:
  contents: write

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1
          cache: pnpm
      - name: Install dependencies
        run: pnpm install

      - name: Install linker
        shell: bash
        run: sudo apt-get install -y mingw-w64

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu

      - name: Build release
        run: make

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/*
